[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "ALAywgGpzDGo25uYh53aUvMmyu5PqEgWahTBw3xukUUY"

[programs.devnet]
marketplace = "BJbuENYJE6FWZ63RzTpPXurEda59wi6iQNN68FFnNSWa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
